name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: uns-release
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}

      - name: 'Extract current package version'
        run: node -p -e '`PACKAGE_VERSION=${"v" + require("./package.json").version}`' >> $GITHUB_ENV

      - uses: oprypin/find-latest-tag@v1
        with:
          repository: unstoppabledomains/uns
        id: latesttag

      - name: Print current package version
        run: echo "${{ env.PACKAGE_VERSION }}"
      - name: Print latest repository tag
        run: echo "${{ steps.latesttag.outputs.tag }}"

      - run: echo "No new version found... Skipping"
        if: steps.latesttag.outputs.tag == env.PACKAGE_VERSION

      - uses: actions/setup-node@v2
        if: steps.latesttag.outputs.tag != env.PACKAGE_VERSION
        with:
          node-version: 20.x

      - run: yarn install --immutable
        if: steps.latesttag.outputs.tag != env.PACKAGE_VERSION

      - run: yarn build:ci
        if: steps.latesttag.outputs.tag != env.PACKAGE_VERSION

      - name: Publish to GitHub Packages
        if: steps.latesttag.outputs.tag != env.PACKAGE_VERSION
        run: yarn npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.latesttag.outputs.tag != env.PACKAGE_VERSION
        with:
          commit_message: Automatic release ${{ env.PACKAGE_VERSION }}
          commit_options: '--no-verify'
          file_pattern: 'artifacts/* dist/* sandbox/state.json sandbox/foundry/foundryup.sh uns-config.json ens-config.json'
          commit_user_name: UNS Release Bot
          commit_user_email: release@unstoppabledomains.com
          commit_author: UNS Release bot <release@unstoppabledomains.com>
          tagging_message: '${{ env.PACKAGE_VERSION }}'
          skip_dirty_check: false
